### ISSUE TITLE
Credential Manifest MUST use JSON Schema Form to encode presentation attributes in JSON

### ISSUE THREAD

**Issue by OR13** [decentralized-identity/credential-manifest#22]
https://github.com/rjsf-team/react-jsonschema-form

`styles` and `display` should be combined.

**Comment by kimdhamilton** [comment]
Question: it wasn't clear whether json schema form supports the path array / fallback style used in this spec. If not, is this  proposing to simplify (i.e., by removing the variations in where the field may appear and fallback)?

**Comment by OR13** [comment]
I don't think it does... that should be clarified... in order to use JSON Schema Form you would probably need to do some transforms..

**Comment by decentralgabe** [comment]
From today's call:

@OR13 
- Can we render JSON Schema Forms across mobile / web?

- How do you imagine combining `styles` and `display`? Can you give us an example / benefits you see in moving it?

**Comment by decentralgabe** [comment]
of course a heavily in-development spec is going to get less hits than an established form solution.

I don't see them as competitors, and I agree *some* implementations of CM would benefit from a standard form mechanism.

**Comment by csuwildcat** [comment]
I don't think there's a fit here for JSON Schema Form to replace what we have as Output Display Objects, because there's still need for a mechanism where Issuers define what smaller set of terse, generic display values are to be 'plucked' from the potentially large credential a wallet receives. Additionally, the goal of the display portion of the spec is not to mandate specific rendered output, but to hand the wallet a simple set of plucked values and suggested styles that map to a small set of basically universal displayable things that any wallet would likely benefit from, vs a wild west section where Issuers can potentially generate massive, divergent, specifically rendered final output that may not be able to be used widely. I don't think there's anything wrong with a wallet turning around and taking the data that gets plucked out and using JSON Schema Form as a potential final rendering tool, but that seems like one step removed from this spec.

**Comment by dtmcg** [comment]
based on the above comments we will close this issue on the next call unless an objection is raised

**Comment by brentzundel** [comment]
no updates, closing
